language: haskell
ghc: 7.8
branches:
  only:
  - source
before_install:
  - git submodule foreach --recursive 'git checkout master; git ls-files | grep -v README | grep -v CNAME | xargs -r git rm'
install:
  - cabal sandbox init
  - cabal install -j --disable-library-profiling --disable-tests --disable-library-coverage --disable-benchmarks --disable-split-objs -fhttps pandoc
  - cabal install -j --disable-library-profiling --disable-tests --disable-library-coverage --disable-benchmarks --disable-split-objs --reorder-goals
before_script:
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"
script: cabal run -j build
after_script:
  - cd _site
  - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
  - git remote add github https://${GH_TOKEN}@${REMOTE}
  - git add --all
  - git status
  - git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
  - git push github master:master | grep -v http
GH_NAME=Travis:
  secure: N4yGsxg4OSa8/71Snae72zlepdnZLlq1D4ymSzzAidgHz7DvggumvnWhT/92X/WReNwMItjLrf2KGl2TllZNvZkLt95wRFukeX8AvHlPDVS0Smf/UqosFCrDNi50kSQLllcZwWzXiJbnIrlK9aILPSEXAuMsxDpy3k5o1bHt5cE=
